// <auto-generated>
// GENERATED from tokens.json by build/tokens.mjs. Do not edit; edit tokens.json and regenerate.
// </auto-generated>

namespace Paddockside.Infrastructure.Email;

/// <summary>Token values for emails, generated from Paddockside.Design/tokens.json (light mode).</summary>
internal static class EmailTokens
{
    public const string FontUi = "Figtree, system-ui, -apple-system, \"Segoe UI\", sans-serif";
    public const string TextSizeMeta = "12px";
    public const string TextSizeSmall = "14px";
    public const string TextSizeBody = "16px";
    public const string TextSizeBodyOwner = "18px";
    public const string TextSizeTitle = "22px";
    public const string TextSizeHeading = "28px";
    public const string TextSizeDisplay = "36px";
    public const string LeadingMeta = "16px";
    public const string LeadingSmall = "20px";
    public const string LeadingBody = "24px";
    public const string LeadingBodyOwner = "28px";
    public const string LeadingTitle = "28px";
    public const string LeadingHeading = "36px";
    public const string LeadingDisplay = "44px";
    public const string Space1 = "4px";
    public const string Space2 = "8px";
    public const string Space3 = "12px";
    public const string Space4 = "16px";
    public const string Space6 = "24px";
    public const string Space8 = "32px";
    public const string Space12 = "48px";
    public const string Space16 = "64px";
    public const string RadiusControl = "6px";
    public const string RadiusCard = "12px";
    public const string RadiusPill = "9999px";

    public const string ColorSurfaceDefault = "#ffffff";
    public const string ColorSurfaceRaised = "#ffffff";
    public const string ColorSurfaceSunken = "#f8f7f4";
    public const string ColorSurfaceQr = "#ffffff";
    public const string ColorTextPrimary = "#171613";
    public const string ColorTextMuted = "#6b665c";
    public const string ColorTextInverse = "#ffffff";
    public const string ColorBorderSubtle = "#e6e3dc";
    public const string ColorBorderStrong = "#8f8a7f";
    public const string ColorActionPrimaryBg = "#1e5a3c";
    public const string ColorActionPrimaryBgHover = "#184a31";
    public const string ColorActionPrimaryFg = "#ffffff";
    public const string ColorActionSecondaryBg = "#f1efea";
    public const string ColorActionSecondaryBgHover = "#e6e3dc";
    public const string ColorActionSecondaryFg = "#171613";
    public const string ColorFocusRing = "#1e5a3c";
    public const string ColorStatusSuccessFg = "#184a31";
    public const string ColorStatusSuccessBg = "#eef6f1";
    public const string ColorStatusWarningFg = "#9a4a07";
    public const string ColorStatusWarningBg = "#fef4e8";
    public const string ColorStatusDangerFg = "#a8231a";
    public const string ColorStatusDangerBg = "#fdf0ee";
    public const string ColorStatusInfoFg = "#1d55a8";
    public const string ColorStatusInfoBg = "#edf3fc";
    public const string ColorScopeInternalFg = "#475467";
    public const string ColorScopeInternalBg = "#f0f2f5";
    public const string ColorScopeOwnersFg = "#0b6670";
    public const string ColorScopeOwnersBg = "#e8f6f7";
    public const string ColorScopeOwnersAtTheTimeFg = "#3940a3";
    public const string ColorScopeOwnersAtTheTimeBg = "#eff0fc";
    public const string ColorScopeNamedPartiesFg = "#7a5212";
    public const string ColorScopeNamedPartiesBg = "#f8f2e6";
    public const string ColorScopeTrainerFg = "#7d2c6e";
    public const string ColorScopeTrainerBg = "#f9eef7";
    public const string ColorKindFactFg = "#1d55a8";
    public const string ColorKindFactBg = "#edf3fc";
    public const string ColorKindMessageFg = "#184a31";
    public const string ColorKindMessageBg = "#eef6f1";
    public const string ColorKindMediaFg = "#5636b8";
    public const string ColorKindMediaBg = "#f2effc";
    public const string ColorKindNoteFg = "#6e5300";
    public const string ColorKindNoteBg = "#fdf6e0";
}
